services:
  aletheia-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aletheia-edge
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
      - ./models:/models
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    restart: unless-stopped
